# Generated by Django 4.0.2 on 2023-01-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
