# Generated by Django 4.0.2 on 2023-06-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_noteuserprofile_created_alter_noteuserprofile_id'),
        ('note', '0004_alter_note_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.noteuserprofile'),
        ),
    ]
