# Generated by Django 4.0.2 on 2023-06-14 13:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_noteuserprofile_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteuserprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='noteuserprofile',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
